### ISSUE TITLE
`npm test` fails

### ISSUE THREAD

**Issue by danielzohar** [galmail/va-experiment#1]
Running `npm test` on a fresh environment causes the following error:
```
> va-experiment@1.0.0 test /Users/danielz/dev/candidates/gal_mail/va-experiment
> jasmine-ts --config=jasmine.json

internal/modules/cjs/loader.js:438
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist' is not defined by "exports" in /Users/danielz/dev/candidates/gal_mail/va-experiment/node_modules/ts-node/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/danielz/dev/candidates/gal_mail/va-experiment/node_modules/jasmine-ts/lib/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
npm ERR! Test failed.  See above for more details.
```

**Comment by galmail** [comment]
oh yeah I know why, so when it happened to me, I quickly fixed it locally by adding this line:
`
"./dist": "./dist/index.js"
`
to the exports of `node_modules/ts-node/package.json`

and completely forgot about it, I should've added at least to the README file. So now I actually found out this issue here:

https://github.com/svi3c/jasmine-ts/issues/45

and the proposed solution is to downgrade ts-node to 8.10.2 (I just pushed the update, it works fine now)
